<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Bookings Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #344767;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            color: #5e72e4;
            font-size: 24px;
        }

        .company-info {
            text-align: center;
            margin-bottom: 30px;
            font-size: 12px;
        }

        .report-info {
            margin-bottom: 30px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }

        .report-info p {
            margin: 5px 0;
        }

        .stats-container {
            margin-bottom: 30px;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }

        .stat-box {
            width: 23%;
            padding: 10px;
            margin-bottom: 15px;
            background-color: #f8f9fa;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }

        .stat-box h3 {
            margin: 0 0 5px 0;
            font-size: 14px;
            color: #8392AB;
        }

        .stat-box p {
            margin: 0;
            font-size: 18px;
            font-weight: bold;
        }

        .stat-box small {
            font-size: 11px;
            color: #8392AB;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        table,
        th,
        td {
            border: 1px solid #E9ECEF;
        }

        th,
        td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #f8f9fa;
            font-size: 12px;
            font-weight: bold;
            color: #8392AB;
        }

        td {
            font-size: 12px;
        }

        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 10px;
            color: #8392AB;
        }

        .text-success {
            color: #2dce89;
        }

        .text-danger {
            color: #f5365c;
        }

        .status-badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .status-pending {
            background-color: #ffeaa7;
            color: #b7791f;
        }

        .status-confirmed {
            background-color: #c6f6d5;
            color: #2f855a;
        }

        .status-in-progress {
            background-color: #bee3f8;
            color: #2b6cb0;
        }

        .status-completed {
            background-color: #c6f6d5;
            color: #2f855a;
        }

        .status-cancelled {
            background-color: #fed7d7;
            color: #c53030;
        }

        .status-no-show {
            background-color: #e2e8f0;
            color: #4a5568;
        }

        .payment-badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .payment-paid {
            background-color: #c6f6d5;
            color: #2f855a;
        }

        .payment-unpaid {
            background-color: #fed7d7;
            color: #c53030;
        }

        .payment-pending {
            background-color: #feebc8;
            color: #c05621;
        }

        .payment-refunded {
            background-color: #bee3f8;
            color: #2b6cb0;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Bookings Report</h1>
    </div>

    <div class="company-info">
        <p>Car Rental Management System</p>
        <p>Casablanca, Morocco</p>
    </div>

    <div class="report-info">
        <p><strong>Period:</strong> {{ date('F d, Y', strtotime($startDate)) }} -
            {{ date('F d, Y', strtotime($endDate)) }}</p>
        <p><strong>Generated On:</strong> {{ date('F d, Y H:i:s') }}</p>
        <p><strong>Generated By:</strong> {{ auth()->user()->name }}</p>
    </div>

    <div class="stats-container">
        <div class="stat-box">
            <h3>Total Bookings</h3>
            <p>{{ number_format($stats['total_bookings']) }}</p>
            <small class="{{ $stats['percent_change'] >= 0 ? 'text-success' : 'text-danger' }}">
                {{ $stats['percent_change'] >= 0 ? '+' : '' }}{{ number_format($stats['percent_change'], 2) }}% vs prev.
                period
            </small>
        </div>

        <div class="stat-box">
            <h3>Daily Average</h3>
            <p>{{ number_format($stats['daily_average'], 1) }}</p>
            <small>Over {{ $stats['days_count'] }} days</small>
        </div>

        <div class="stat-box">
            <h3>Completion Rate</h3>
            <p>{{ number_format($stats['completion_rate'], 1) }}%</p>
            <small>{{ number_format($stats['cancellation_rate'], 1) }}% cancellation</small>
        </div>

        <div class="stat-box">
            <h3>Avg. Value</h3>
            <p>{{ number_format($stats['avg_booking_value'], 2) }} MAD</p>
            <small>Per booking</small>
        </div>
    </div>

    <h2>Booking Details</h2>
    <table>
        <thead>
            <tr>
                <th>Booking #</th>
                <th>Date</th>
                <th>Customer</th>
                <th>Vehicle</th>
                <th>Period</th>
                <th>Status</th>
                <th>Payment</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($bookings as $booking)
                <tr>
                    <td>{{ $booking->booking_number }}</td>
                    <td>{{ $booking->created_at->format('Y-m-d') }}</td>
                    <td>{{ $booking->customer_name }}</td>
                    <td>{{ $booking->car ? $booking->car->brand_name . ' ' . $booking->car->model : 'N/A' }}</td>
                    <td>{{ $booking->pickup_date->format('Y-m-d') }} to {{ $booking->dropoff_date->format('Y-m-d') }}</td>
                    <td>
                        <span class="status-badge status-{{ $booking->status }}">
                            {{ ucfirst($booking->status) }}
                        </span>
                    </td>
                    <td>
                        <span class="payment-badge payment-{{ $booking->payment_status }}">
                            {{ ucfirst($booking->payment_status) }}
                        </span>
                    </td>
                    <td>{{ number_format($booking->total_amount, 2) }} MAD</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report is automatically generated. Please contact the system administrator for any inquiries.</p>
        <p>© {{ date('Y') }} Car Rental Management System</p>
    </div>
</body>

</html>