<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Revenue Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #344767;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            color: #5e72e4;
            font-size: 24px;
        }

        .company-info {
            text-align: center;
            margin-bottom: 30px;
            font-size: 12px;
        }

        .report-info {
            margin-bottom: 30px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }

        .report-info p {
            margin: 5px 0;
        }

        .stats-container {
            margin-bottom: 30px;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }

        .stat-box {
            width: 23%;
            padding: 10px;
            margin-bottom: 15px;
            background-color: #f8f9fa;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }

        .stat-box h3 {
            margin: 0 0 5px 0;
            font-size: 14px;
            color: #8392AB;
        }

        .stat-box p {
            margin: 0;
            font-size: 18px;
            font-weight: bold;
        }

        .stat-box small {
            font-size: 11px;
            color: #8392AB;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        table,
        th,
        td {
            border: 1px solid #E9ECEF;
        }

        th,
        td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #f8f9fa;
            font-size: 12px;
            font-weight: bold;
            color: #8392AB;
        }

        td {
            font-size: 12px;
        }

        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 10px;
            color: #8392AB;
        }

        .text-success {
            color: #2dce89;
        }

        .text-danger {
            color: #f5365c;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Revenue Report</h1>
    </div>

    <div class="company-info">
        <p>Car Rental Management System</p>
        <p>Casablanca, Morocco</p>
    </div>

    <div class="report-info">
        <p><strong>Period:</strong> {{ date('F d, Y', strtotime($startDate)) }} -
            {{ date('F d, Y', strtotime($endDate)) }}</p>
        <p><strong>Generated On:</strong> {{ date('F d, Y H:i:s') }}</p>
        <p><strong>Generated By:</strong> {{ auth()->user()->name }}</p>
    </div>

    <div class="stats-container">
        <div class="stat-box">
            <h3>Total Revenue</h3>
            <p>{{ number_format($stats['total_revenue'], 2) }} MAD</p>
            <small class="{{ $stats['percent_change'] >= 0 ? 'text-success' : 'text-danger' }}">
                {{ $stats['percent_change'] >= 0 ? '+' : '' }}{{ number_format($stats['percent_change'], 2) }}% vs prev.
                period
            </small>
        </div>

        <div class="stat-box">
            <h3>Daily Average</h3>
            <p>{{ number_format($stats['daily_average'], 2) }} MAD</p>
            <small>Over {{ $stats['days_count'] }} days</small>
        </div>

        <div class="stat-box">
            <h3>Payment Count</h3>
            <p>{{ number_format($stats['payments_count']) }}</p>
            <small>Avg: {{ number_format($stats['avg_payment'], 2) }} MAD</small>
        </div>

        <div class="stat-box">
            <h3>Previous Period</h3>
            <p>{{ number_format($stats['previous_revenue'], 2) }} MAD</p>
            <small>Same duration</small>
        </div>
    </div>

    <h2>Payment Details</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Amount</th>
                <th>Method</th>
                <th>Reference</th>
                <th>Customer</th>
                <th>Vehicle</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $payment)
                <tr>
                    <td>{{ date('Y-m-d', strtotime($payment->payment_date)) }}</td>
                    <td>{{ number_format($payment->amount, 2) }} MAD</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $payment->payment_method)) }}</td>
                    <td>{{ $payment->reference ?? 'N/A' }}</td>
                    <td>{{ $payment->contract && $payment->contract->client ? $payment->contract->client->name : 'N/A' }}
                    </td>
                    <td>{{ $payment->contract && $payment->contract->car ? $payment->contract->car->brand_name . ' ' . $payment->contract->car->model : 'N/A' }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report is automatically generated. Please contact the system administrator for any inquiries.</p>
        <p>© {{ date('Y') }} Car Rental Management System</p>
    </div>
</body>

</html>